name = "DiscreteValueIteration"
uuid = "4b033969-44f6-5439-a48b-c11fa3648068"
repo = "https://github.com/JuliaPOMDP/DiscreteValueIteration.jl.git"
version = "0.4.4"

[deps]
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
POMDPLinter = "0.1"
POMDPModelTools = "0.1.7, 0.2, 0.3"
POMDPPolicies = "0.1.4, 0.2, 0.3, 0.4"
POMDPs = "0.8, 0.9"
julia = "1"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "POMDPModels", "DelimitedFiles"]
